[build]
builder = "NIXPACKS"
buildCommand = "npx -y pnpm@10.33.0 --filter @bin/web build"

[deploy]
startCommand = "npx -y pnpm@10.33.0 --filter @bin/web start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
